### ISSUE TITLE
Refresh report panel after generating second report

### ISSUE THREAD

**Issue by stoyelq** [inSileco/shinySpatialApp_origin#25]
Steps to reproduce: generate a report using the app and then either select a new study area or change the section selections and generate a second report.
Expected behaviour: Report panel updates to show the new report, first report can be entirely deleted.
Actual behaviour: Report is generated in the output file, but is not updated in the shiny app panel.

**Comment by KevCaz** [comment]
The problem was that the reactive expression was not re-executed when the path to the HTML version of the report was unchanged. I took care of that problem for both full and the custom reports.

**Comment by KevCaz** [comment]
@stoyelq we made the handling of Rmd parts easier, see 86cc42e . In a nutshell, there is a unique way to add a section in the Rmd, not 3!

**Comment by stoyelq** [comment]
The refresh is working on my end, the new Rmd handling looks great too!
