### ISSUE TITLE
Generalize process of adding new templates

### ISSUE THREAD

**Issue by stoyelq** [inSileco/shinySpatialApp_origin#27]
Fairly minor, but it would be nice to be able to add new templates without needing to update the render_full_report function. Beyond adding the actually template file, the only other file that should need to be updated should be UI function in the module file.  

Don't worry about this too much though, it is by no means essential.

**Comment by david-beauchesne** [comment]
@stoyelq we modified the `render_full_report` function to remove the need to specify the sections that are to be added to the report. Everything is now done directly in the `fullReportUI` module by directly using the path to individual rmarkdowns as the names of the checkbox inputs. Let us know if that makes more sense on your side.

**Comment by stoyelq** [comment]
Yes, this way of doing things makes a lot of sense on my side, it all feels a lot more streamlined now.
